name: CI Workflow #name of flow

on:
  #this block tells github action to execute it only when push or pull request on "main"
  push:
    branches:
    #specify which branch affected
    - main
  pull_request:
    branches:
    - main

jobs:
  #what to execute 
  test:
    runs-on: ubuntu-latest

    steps:
    #steps to execute in the memtioned os
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2 #install py version mentioned
      with:
        python-version: '3.9'

    - name: Install dependencies #for githubaction server installing these 
      run: |
        python -m pip install --upgrade pip
        pip install pytest streamlit

    - name: Run tests #execute these tests in the script (optional step)
      run: |
        pytest _test.py
